DROP TABLE IF EXISTS PHONE;
DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
    ID VARCHAR(255) PRIMARY KEY, 
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    CREATED DATE,
    MODIFIED DATE,
    LAST_LOGIN DATE,
    TOKEN VARCHAR(4000),
    ISACTIVE INT
);

CREATE TABLE PHONE (
    ID VARCHAR(255) PRIMARY KEY, 
    IDUSUARIO INT,
    NUMBER VARCHAR(20),
    CITYCODE VARCHAR(5),
    CONTRYCODE VARCHAR(5),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID)
);